"""Expand customer and employee models with correct constraints

Revision ID: 42156f710a72
Revises: 
Create Date: 2025-08-22 20:54:02.363288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42156f710a72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_kunde')
    with op.batch_alter_table('kunde', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zustand', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tag', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('hausnummer', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('erreichbarkeit', sa.Text(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_kunde_email', ['email'])
        batch_op.drop_column('durchwahl_buero')
        batch_op.drop_column('abteilung')
        batch_op.drop_column('telefon_privat')
        batch_op.drop_column('faxnummer')
        batch_op.drop_column('anschriftswahl')
        batch_op.drop_column('firma2')

    with op.batch_alter_table('mitarbeiter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zustand', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tag', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('titel', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('firma', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('strasse', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('hausnummer', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('plz', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ort', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('land', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_mitarbeiter_email', ['email'])
        batch_op.drop_column('firma_plz')
        batch_op.drop_column('firmenname')
        batch_op.drop_column('durchwahl')
        batch_op.drop_column('firma_strasse')
        batch_op.drop_column('firma_ort')
        batch_op.drop_column('telefon')
        batch_op.drop_column('abteilung')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mitarbeiter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abteilung', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('telefon', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('firma_ort', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('firma_strasse', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('durchwahl', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('firmenname', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('firma_plz', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint('uq_mitarbeiter_email', type_='unique')
        batch_op.drop_column('land')
        batch_op.drop_column('ort')
        batch_op.drop_column('plz')
        batch_op.drop_column('hausnummer')
        batch_op.drop_column('strasse')
        batch_op.drop_column('firma')
        batch_op.drop_column('titel')
        batch_op.drop_column('tag')
        batch_op.drop_column('zustand')

    with op.batch_alter_table('kunde', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firma2', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('anschriftswahl', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('faxnummer', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('telefon_privat', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('abteilung', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('durchwahl_buero', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint('uq_kunde_email', type_='unique')
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('erreichbarkeit')
        batch_op.drop_column('hausnummer')
        batch_op.drop_column('tag')
        batch_op.drop_column('zustand')

    op.create_table('_alembic_tmp_kunde',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titel', sa.VARCHAR(length=50), nullable=True),
    sa.Column('anrede', sa.VARCHAR(length=20), nullable=True),
    sa.Column('vorname', sa.VARCHAR(length=100), nullable=True),
    sa.Column('nachname', sa.VARCHAR(length=100), nullable=False),
    sa.Column('strasse', sa.VARCHAR(length=200), nullable=True),
    sa.Column('postleitzahl', sa.VARCHAR(length=20), nullable=True),
    sa.Column('ort', sa.VARCHAR(length=100), nullable=True),
    sa.Column('land', sa.VARCHAR(length=100), nullable=True),
    sa.Column('firma1', sa.VARCHAR(length=150), nullable=True),
    sa.Column('funktion', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('telefon_beruflich', sa.VARCHAR(length=50), nullable=True),
    sa.Column('mobil_telefon', sa.VARCHAR(length=50), nullable=True),
    sa.Column('anmerkungen', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('mitarbeiter_id', sa.INTEGER(), nullable=True),
    sa.Column('zustand', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tag', sa.VARCHAR(length=100), nullable=True),
    sa.Column('hausnummer', sa.VARCHAR(length=20), nullable=True),
    sa.Column('erreichbarkeit', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['mitarbeiter_id'], ['mitarbeiter.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name=op.f('uq_kunde_email'))
    )
    # ### end Alembic commands ###
