"""Add is_standard to Vorlage

Revision ID: 90ced2d3e5b4
Revises:
Create Date: 2025-08-25 07:59:22.759082

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "90ced2d3e5b4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vorlage", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_standard",
                sa.Boolean(),
                nullable=False,
                # KORREKTUR: Fügt einen Standardwert für bestehende Zeilen hinzu
                server_default="0",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vorlage", schema=None) as batch_op:
        batch_op.drop_column("is_standard")

    # ### end Alembic commands ###
