"""Add detailed attributes to Kunde and Mitarbeiter

Revision ID: e89f79af13da
Revises: 42156f710a72
Create Date: 2025-08-22 20:58:42.613949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89f79af13da'
down_revision = '42156f710a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kunde', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geburtsdatum', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('notizen', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('firma', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('position', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('telefon', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('plz', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bevorzugter_kontaktweg', sa.String(length=100), nullable=True))
        batch_op.drop_column('funktion')
        batch_op.drop_column('firma1')
        batch_op.drop_column('telefon_beruflich')
        batch_op.drop_column('postleitzahl')
        batch_op.drop_column('anmerkungen')
        batch_op.drop_column('mobil_telefon')
        batch_op.drop_column('erreichbarkeit')

    with op.batch_alter_table('mitarbeiter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geburtsdatum', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('notizen', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('telefon', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mitarbeiter', schema=None) as batch_op:
        batch_op.drop_column('telefon')
        batch_op.drop_column('notizen')
        batch_op.drop_column('geburtsdatum')

    with op.batch_alter_table('kunde', schema=None) as batch_op:
        batch_op.add_column(sa.Column('erreichbarkeit', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('mobil_telefon', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('anmerkungen', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('postleitzahl', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('telefon_beruflich', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('firma1', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('funktion', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('bevorzugter_kontaktweg')
        batch_op.drop_column('plz')
        batch_op.drop_column('telefon')
        batch_op.drop_column('position')
        batch_op.drop_column('firma')
        batch_op.drop_column('notizen')
        batch_op.drop_column('geburtsdatum')

    # ### end Alembic commands ###
